services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_semantic_search
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semantic_search
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d semantic_search"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  init_db:
    image: pgvector/pgvector:pg17
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      sh -c "
      echo 'Waiting for PostgreSQL...';
      until pg_isready -h postgres -U postgres; do
        sleep 2;
      done;

      echo 'Creating vector extension...';
      PGPASSWORD=postgres psql postgresql://postgres:postgres@postgres:5432/semantic_search \
      -v ON_ERROR_STOP=1 \
      -c 'CREATE EXTENSION IF NOT EXISTS vector;';

      echo 'Init finished!';
      "
    restart: "no"

volumes:
  postgres_data:
